version: '3.4'
services:
  app:
    build:
      context: app
    command: java -jar ./app.jar
    image: 'virusdb'
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    build:
      context: postgres
    image: 'postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    volumes:
      - "db-data:/var/lib//postgresql/data"
  js:
    build:
      context: js
    image: 'virusdb-ui'
    ports: 
      - "8081:8081"
    depends_on:
      - app
volumes:
  db-data:
